#!/bin/bash

###############################################################################
#
#   An utility script to checking which Java version compiled each submodule
#   of this project.
#
###############################################################################

echo "===================================================="
echo "Verifying Java version for classes within JAR files."
echo ""
echo "  testclock must be 52 (Java 8)"
echo ""
echo "Note that JAR files must exist (./gradlew build)."
echo ""

echo "===== testclock ===="
javap \
    -verbose \
    -classpath build/libs/testclock-*-SNAPSHOT.jar \
    io.github.malczuuu.testclock.TestClock \
    | grep "major version"
